### PR TITLE
fix #7 by calculating whether the value was positive or negative

### LINKED ISSUE #7: Lats & Longs less than +1 minute are in the wrong direction
These lines fail when added to the test suite:

```js
assert.equal('N', magellan(0.1).latitude().coordinate.direction);
assert.equal('E', magellan(0.1).longitude().coordinate.direction);
```

They are evaluated at `S` and `W` respectively.

### PR DESCRIPTION
**Pull request by richorama**
I have the tests passing, but it feels like this is more complicated than is should be.

### CODE REVIEW

File: magellan.js [hunk 1]
```diff
@@ -33,6 +33,8 @@
 	            coordinate.degrees = parseInt(args[0]);
 	            coordinate.minutes = parseInt(args[1]);
 	            coordinate.seconds = parseFloat(args[2]);
+
+	            var isPositive = parseInt(args[0]) >= 0;
```
Comment (captivationsoftware) [inline magellan.js]: No need to parseInt again:

var isPositive = coordinate.degrees >= 0

**Comment by richorama** [comment]
I have updated that line, thanks for the suggestion.
